### ISSUE TITLE
In IE10, trying to create a Web Worker from a blob:-URL throws a SecurityError

### ISSUE THREAD

**Issue by quatrano** [cytoscape/foograph#14]
I don't know if this issue is specific to this layout, or cytoscape.js in general:

We're trying to use the foograph layout in IE10, but a SecurityError is thrown.  This is a known issue with IE10 and there's a known workaround:

http://stackoverflow.com/questions/10343913/how-to-create-a-web-worker-from-a-string

**Comment by maxkfranz** [comment]
That's not a workaround.  That recommends using a separate file for the worker, which is not an option -- and not a solution for blobs.  IE10 has broken support for webworkers.  

If you want to use layouts like spread, you will have to use an evergreen/modern browser like IE-latest or Edge.  If you want to support outdated browsers, you'll have to work around their technical limitations by using more basic layouts etc.
